---
controller_projects:
  - name: Fact Scan
    organization: Default
    scm_type: git
    scm_url: 'https://github.com/heatmiser/awx-facts-playbooks.git'

  - name: Three Tier App
    organization: Default
    scm_type: git
    scm_url: 'https://github.com/heatmiser/ansible-3tier-app.git'
    scm_branch: development
    scm_delete_on_update: true
    scm_update_on_launch: true
    scm_update_cache_timeout: 3600
    default_environment: auto_satellite workshop execution environment

  - name: Demo Project
    organization: Default
    # scm_type: git
    # scm_url: 'https://github.com/ansible/ansible-tower-samples.git'
    state: absent
...
