---
- name: Miscellaneous host configuration
  hosts: "{{ dynamic_inventory_group | default(omit) }}"
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  tasks:
    - name: Configure EL7 systems
      when: ansible_distribution_major_version | int == 7
      ansible.builtin.import_tasks: misc_host_config_rhel7.yml
    - name: Configure RHEL8 systems
      when: ansible_distribution_major_version | int == 8
      ansible.builtin.import_tasks: misc_host_config_rhel8.yml

  handlers:
    - name: "Rebuild grub.cfg"
      ansible.builtin.command: >-
        grub2-mkconfig -o /boot/grub2/grub.cfg
...
