---
satellite_activation_keys:
  # Red Hat Enterprise Linux 7
  - name: "RHEL7_Dev"
    lifecycle_environment: "RHEL7_Dev"
    content_view: "RHEL7"
  - name: "RHEL7_QA"
    lifecycle_environment: "RHEL7_QA"
    content_view: "RHEL7"
  - name: "RHEL7_Prod"
    lifecycle_environment: "RHEL7_Prod"
    content_view: "RHEL7"
  # Red Hat Enterprise Linux 8
  - name: "RHEL8_Dev"
    lifecycle_environment: "RHEL8_Dev"
    content_view: "RHEL8"
    release_version: "8.8"
  - name: "RHEL8_QA"
    lifecycle_environment: "RHEL8_QA"
    content_view: "RHEL8"
    release_version: "8.8"
  - name: "RHEL8_Prod"
    lifecycle_environment: "RHEL8_Prod"
    content_view: "RHEL8"
    release_version: "8.8"
  # Oracle Linux 7
  - name: "OL7_Dev"
    lifecycle_environment: "OL7_Dev"
    content_view: "OL7"
  - name: "OL7_QA"
    lifecycle_environment: "OL7_QA"
    content_view: "OL7"
  - name: "OL7_Prod"
    lifecycle_environment: "OL7_Prod"
    content_view: "OL7"
...
