---
satellite_lifecycle_environments:
  # Red Hat Enterprise Linux 7
  - name: "RHEL7_Dev"
    prior: "Library"
  - name: "RHEL7_QA"
    prior: "RHEL7_Dev"
  - name: "RHEL7_Prod"
    prior: "RHEL7_QA"
  # Community Enterprise Linux 7
  - name: "CentOS7_Dev"
    prior: "Library"
  - name: "CentOS7_QA"
    prior: "CentOS7_Dev"
  - name: "CentOS7_Prod"
    prior: "CentOS7_QA"
  # CentOS7 to RHEL7 conversion
  - name: "CentOS7_to_RHEL7_Dev"
    prior: "Library"
  - name: "CentOS7_to_RHEL7_QA"
    prior: "CentOS7_to_RHEL7_Dev"
  - name: "CentOS7_to_RHEL7_Prod"
    prior: "CentOS7_to_RHEL7_QA"
...
